name: Build and test the package
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  package:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        pyver: [3.6,3.7,3.8]
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build the test root environment
      run: |
          [ $RUNNER_OS = 'Windows' ] && CONDA_EXE=$CONDA/Scripts/conda.exe
          [ $RUNNER_OS == macOS ] && export CONDA_PKGS_DIRS=~/.pkgs
          ${CONDA_EXE:-conda} create -p ../conda conda conda-build conda-verify python=${{ matrix.pyver }} pillow>=3.1 ruamel_yaml conda-forge::codecov pytest pytest-cov
    - name: Build, unit test, and install the package
      run: |
          source ../conda/etc/profile.d/conda.sh
          conda build conda.recipe --python=${{ matrix.pyver }} --no-test
          conda install local::constructor
    - name: Run tests
      run: |
        source ../conda/etc/profile.d/conda.sh
        conda activate
        constructor -V
        pytest --pyargs -v --cov=constructor constructor
        python scripts/run_examples.py
